# flutter_native_splash-production.yaml
flutter_native_splash:
  color: "#f9d924"
  image: assets/img/splash.png
  #branding: assets/icon/icon.png
  color_dark: "#f9d924"
  image_dark: assets/img/splash.png
  #branding_dark: assets/icon/icon.png

  android_12:
    image: assets/img/splash.png
    icon_background_color: "#f9d924"
    image_dark: assets/img/splash.png
    icon_background_color_dark: "#f9d924"

  android: true
  ios: false
  web: false
